### PR TITLE
Windows git bash make

### PR DESCRIPTION
**Pull request by capnramses**
Reason for PR

* Using git-bash to build on Windows complains when hitting some file-copy and clean commands  that are Windows-specific.
* I also spotted a warning from MSVC in recent code changes for directory creation (a return statement was unreachable on Windows but not Linux).

Changes in PR

* Removed windows-specific post-build dll copies from Makefile on Windows so that git-bash was happy. This sounds odd but I also just switched to git-bash as a terminal in vscode and it is a bit clearer for managing git branches etc than powershell or cmd. It's also perhaps a more common gcc environment now on windows than mingw packages via cmd.
* To avoid multi-system file copies on build I just made a duplicate of the .dll files required. Wasteful but simpler.

Testing Summary

* Tested with MSVC (also found a v minor omission from the .bat helper with a missing "cd.." here i fixed).
* Tested makefile on cmd, powershell, and git-bash.

Risk introduced by PR

* Repo & download space wasted by .dll files to make it easier for Windows builds. It feels messy to save an instruction step. Open to suggestions.

### CODE REVIEW

**Review by valeria-volu — COMMENTED** [review]
@capnramses Quick question - this branch does not have --output-dir change. Does this matter?

**Comment by capnramses** [comment]
> @capnramses Quick question - this branch does not have --output-dir change. Does this matter?

i think it's fine since i already merged that PR and the diff isn't showing that it's removing it

**Comment by capnramses** [comment]
an alternative here would be:

* create a bin/ subdir for .exe output and have the .dll files in there already
* remove the .dll files from the ffmpeg third party folder

**Review by valeria-volu — APPROVED** [review]
Tested on Windows 10

**Pull request merged**
