### PR TITLE
first upload of ct-vols

### PR DESCRIPTION
**Pull request by capnramses**
Reason for PR:

* Moving existing internal ct-vols tool into public vol_cl_tools suite.

Changes in PR:

* Added new licence/copyright/version header to ct-vols files.
* Removed Dockerfile since cmake/make is more consistent with existing tool build.
* Added build and usage instructions to header and Readme.
* Added a version number to ct-vols (0.3).
* clang-format.

Testing Summary:

* Tested build instructions work on Ubuntu and tested tool works on 1 sequence I had.

Risk of Merging PR

* Only tested on Linux - tool was never supported on Windows/MacOS. The Dockerfile helped here but I think we could just add support for Windows/macOS in a future PR. It may work out of the box with macOS with a brew install of FFmpeg. Could also put the Dockerfile back in but it should probably support all tools then.

### CODE REVIEW

**Review by patrick-volograms — APPROVED** [review]

**Review by valeria-volu — APPROVED** [review]

**Comment by valeria-volu** [comment]
Quick comment - should we give this tool a more readable name. For example, "cut-volu"?

**Comment by capnramses** [comment]
> Quick comment - should we give this tool a more readable name. For example, "cut-volu"?

yes let's do it!

cutvols or volscut maybe?

**Comment by valeria-volu** [comment]
either is good @capnramses

**Comment by capnramses** [comment]
renamed from ct-vols to cutvols (seemed sensible to keep it similar to original name).
compiled on windows - seems to work

**Pull request merged**
